version: 2.1

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build

jobs:
  # build:
  #   working_directory: ~/mern-starter
  #   docker:
  #     - image: circleci/node:10.16.3
  #     - image: mongo:4.2.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: 'sudo npm install -g npm@5'
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #         paths:
  #           - ./node_modules
  #     - run:
  #         name: test
  #         command: npm test
  #     - run:
  #         name: code-coverage
  #         command: './node_modules/.bin/nyc report --reporter=text-lcov'
  #     - store_artifacts:
  #         path: test-results.xml
  #         prefix: tests
  #     - store_artifacts:
  #         path: coverage
  #         prefix: coverage
  #     - store_test_results:
  #         path: test-results.xml
  executor:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
            --template-file ./ec2-on-the-fly/resources.yml \
            --stack-name temp-stack


workflows:
  pipeline:
    jobs:
      # - build
      # - test: 
      #     requires:
      #       - build
      # - analyze:
      #     requires:
      #       - test
      - executor

